export const CROP_EMOJI: Record<string, string> = {
  rice:        "🌾",
  maize:       "🌽",
  apple:       "🍎",
  grapes:      "🍇",
  watermelon:  "🍉",
  muskmelon:   "🍈",
  orange:      "🍊",
  banana:      "🍌",
  mango:       "🥭",
  coconut:     "🥥",
  coffee:      "☕",
  cotton:      "🌿",
  jute:        "🌿",
  papaya:      "🍑",
  pomegranate: "🍎",
  blackgram:   "🫘",
  chickpea:    "🫘",
  kidneybeans: "🫘",
  lentil:      "🫘",
  motherbeans: "🫘",
  mungbean:    "🫘",
  pigeonpeas:  "🫘",
};
